### ISSUE TITLE
정권아

### ISSUE THREAD

**Issue by kjw0612** [kjw0612/awesome-random-forest#1]
이게 random forest 라고 이름짓긴 했는데, 사실 넓게는 tree (뉴럴에서의 network말고) 갖고 하는 방법들 decision tree, additive tree, boosting, ensemble 등도 종국엔 다 포함했으면 해~

**Comment by deruci** [comment]
알겠습니다. 최근 NIPS나 ICML 쪽부터 찾아서 포함시켜 볼게요. 아예 theory 쪽에 paper들을 그런식으로 분류해 보면 좋겠네요

**Comment by kjw0612** [comment]
오 굳굳!
